### ISSUE TITLE
Error in config

### ISSUE THREAD

**Issue by MrNeeony** [ChestShop-authors/ChestShop-3#336] opened 2020-07-04 18:20 UTC
#### Plugin Version
[The full plugin version that you are running from /version ChestShop]
 Version for 1.12.2 (3.1.12)
#### Plugin Config
[The full config.yml file of ChestShop]
https://paste.hostify.cz/?3fa427d4ae0d930b#41T5i6zXjE3fPm6F6YLddLBeCf7b5nCYTt56nSTmgBCX
 
#### Server Version
[The full server version that you are running from /version]
1.12.2 Spigot
 
#### Server Log
[The full latest.log file, especially important if you have a stack trace]
https://paste.hostify.cz/?401f3e781746fe0e#H8mamW7NRssaYX75w3ek8z9LpBAA8p5m1vSVZpW2Cq4u

#### What other plugins are you running?
[List of your plugins, ideally with the version] 
https://pasteboard.co/Jg7RRET.png
https://pasteboard.co/Jg7S4Sr.png

#### What is happening?
[Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures and the full error log!]
I don't understand the error log, I'd like to report it.
(that log is up) 

#### What did you expect to happen?
[Explain what you expected to happen after performing the previously described steps]
I'm worried about that log.

### Additional context
[Add any other context or screenshots about the feature request here.]

[And Delete the lines in square brackets!]

**Comment by Phoenix616** [comment] 2020-07-04 18:30
You are running an extremely outdated version of this plugin, update to the [latest builds](https://ci.minebench.de/job/ChestShop-3-1.12/) for your server version and see if the issue still occurs.

**Comment by Phoenix616** [comment] 2020-07-04 18:32
DUplicate of #49. Please post your server version (from /version) as well as some information about your setup (Operating system version, jvm type and version) in ticket #49.

**Closed by Phoenix616** 2020-07-04 18:32 UTC
Labels: 1.12, outdated version

**Comment by MrNeeony** [comment] 2020-07-04 18:37
20:36:47[INFO] This server is running CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
20:36:47[INFO] Checking version, please wait...
20:36:48[INFO] You are 1080 version(s) behind
