### ISSUE TITLE
chestshop problems. I know it isnt a problem but it keeps on giving me warn everytime on restarting the server 

### ISSUE THREAD

**Issue by Drainer2002** [ChestShop-authors/ChestShop-3#326] opened 2020-06-19 10:24 UTC
> [12:13:41 WARN]: 105 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating table 'items'
> [12:13:41 WARN]: 117 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `items` (`id` INTEGER PRIMARY KEY AUTOINCREMENT , `code` VARCHAR NOT NULL , UNIQUE (`code`))
> [12:13:41 WARN]: 124 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating table 'accounts'
> [12:13:41 WARN]: 124 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating index 'accounts_uuid_idx' for table 'accounts
> [12:13:41 WARN]: 124 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating index 'accounts_shortName_idx' for table 'accounts
> [12:13:41 WARN]: 124 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating index 'accounts_name_idx' for table 'accounts
> [12:13:41 WARN]: 126 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `accounts` (`name` VARCHAR NOT NULL , `shortName` VARCHAR NOT NULL , `uuid` VARCHAR NOT NULL , `lastSeen` BIGINT DEFAULT 0 NOT NULL , PRIMARY KEY (`shortName`) , UNIQUE (`name`,`uuid`) )
> [12:13:41 WARN]: 126 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_uuid_idx` ON `accounts` ( `uuid` )
> [12:13:41 WARN]: 126 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_shortName_idx` ON `accounts` ( `shortName` )
> [12:13:41 WARN]: 127 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_name_idx` ON `accounts` ( `name` )

**Comment by Phoenix616** [comment] 2020-06-19 10:29
These are info messages as indicated by the `INFO` in the message. Also this is a duplicate of #49 so if you have any more details about your setup the please provide them there, it is still not clear why this shows up on some setups and not others.

**Closed** 2020-06-19 10:29 UTC
Labels: duplicate
