### ISSUE TITLE
Could not pass event PreTransactionEvent to ChestShop v3.12

### ISSUE THREAD

**Issue by andrewkm** [ChestShop-authors/ChestShop-3#457] opened 2021-06-17 06:10 UTC
ChestShop: Build 307
Config: https://pastebin.com/pT2LbGxJ

```
[02:08:59] [Server thread/ERROR]: Could not pass event PreTransactionEvent to ChestShop v3.12 (build 307)
java.lang.StackOverflowError: null
	at com.Acrobot.ChestShop.Libs.Kyori.adventure.text.AbstractComponent.asComponents(AbstractComponent.java:54) ~[?:?]
	at com.Acrobot.ChestShop.Libs.Kyori.adventure.text.AbstractComponent.asComponents(AbstractComponent.java:50) ~[?:?]
	at com.Acrobot.ChestShop.Libs.Kyori.adventure.text.AbstractComponent.<init>(AbstractComponent.java:88) ~[?:?]
	at com.Acrobot.ChestShop.Libs.Kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:53) ~[?:?]
	at com.Acrobot.ChestShop.Libs.Kyori.adventure.text.TextComponentImpl$BuilderImpl.build(TextComponentImpl.java:147) ~[?:?]
	at com.Acrobot.ChestShop.Libs.Kyori.adventure.text.TextComponentImpl$BuilderImpl.build(TextComponentImpl.java:115) ~[?:?]
	at com.Acrobot.ChestShop.Libs.Kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:268) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:207) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
```

**Comment by Phoenix616** [comment] 2021-06-17 09:21
Duplicate of #454

**Closed** 2021-06-17 09:21 UTC
Labels: duplicate
