### ISSUE TITLE
Glow inksac

### ISSUE THREAD

**Issue by LogGits** [ChestShop-authors/ChestShop-3#472] opened 2021-08-21 00:47 UTC
### Is your feature request related to a problem? Please describe.

Some signs are incredibly difficult to see.

### Describe the solution you'd like

I'd like to be able to use glowinksac (maybe even colours and debug stick idk) in 1.17.1 and the custom sign colours to make shops seem easier to read.

### Describe alternatives you've considered

hologram plugins but that gets too annoying.

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I have checked that the latest build doesn't already implement the feature.

**Comment by Phoenix616** [comment] 2021-08-21 15:39
Duplicate of #466

**Closed** 2021-08-21 15:39 UTC
Labels: enhancement
