### ISSUE TITLE
Item-Name Format

### ISSUE THREAD

**Issue by Leahcimkrob** [ChestShop-authors/ChestShop-3#426] opened 2021-03-26 10:02 UTC
#### Is your feature request related to a problem? Please describe.
Item-Names in other language

#### Describe the solution you'd like
It's possible to use MC-Itemnames for ItemAlias like SPRUCE_PLANKS?

**Comment by Phoenix616** [comment] 2021-03-26 14:23
Duplicate of #398

**Closed by Phoenix616** 2021-03-26 14:23 UTC
Labels: duplicate, enhancement
