### ISSUE TITLE
Possible to add users to a chestshop?

### ISSUE THREAD

**Issue by andrewkm** [ChestShop-authors/ChestShop-3#358] opened 2020-09-20 13:46 UTC
Is it possible to add users to a chest shop so they can help you maintain it.
Perhaps with LWC's **cmodify username** function? (As in cmodifying the user to the chestshop chest, so they can add/remove items from it). This would be really helpful for several users.

If helpful our current config looks as such: https://pastebin.com/raw/N8sfHHZ2

**Comment by Phoenix616** [comment] 2020-09-20 13:52
Duplicate of #173 

And yes, using LWC to auto-protect shops instead of the built in protection should already allow access of multiple people to a shop.

**Closed by Phoenix616** 2020-09-20 13:52 UTC
Labels: enhancement

**Comment by andrewkm** [comment] 2020-09-20 14:35
So looking at my config, I would need to turn the following two options to "true" @Phoenix616 ?

```
#EXPERIMENTAL: Do you want to turn off the default protection when another plugin is protecting the block? (Will leave the chest visually open - CraftBukkit bug!)
TURN_OFF_DEFAULT_PROTECTION_WHEN_PROTECTED_EXTERNALLY: true
#Do you want to turn off the default sign protection? Warning! Other players will be able to destroy other people's shops!
TURN_OFF_SIGN_PROTECTION: true
```

**Comment by Phoenix616** [comment] 2020-09-20 14:37
Iirc only TURN_OFF_DEFAULT_PROTECTION_WHEN_PROTECTED_EXTERNALLY would need
to be true, the sign one shouldn't influence chest access.
