### ISSUE TITLE
Server Thread/Warn INFO in Console

### ISSUE THREAD

**Issue by Breakaway321** [ChestShop-authors/ChestShop-3#388] opened 2020-12-27 18:58 UTC
#### Plugin Version

 3.11
 
#### Plugin Config

<details>
  <summary>Config</summary>
  
 ```yaml
 Config is set to the default settings.
 ```
 
 </details>
 
#### Server Version

 1.14
 
#### Server Log

<details>
  <summary>Log</summary>

```
https://pastebin.com/gyQpddNF
```

</details>

#### What other plugins are you running?

LuckPerms, WorldEdit, PlaceholderAPI, SuperTrailsPro, RankSync, BuycraftX, Multiverse-Core, ProtocolLib, WorldGuard, JetCharacters, CraftingStore, Vault, dynmap, MyPet, AdvancedRegionMarket, Essentials, BKCommonLib, GCore, Herochat, TheNewEconomy, EpicRename, LightCleaner, WorldBorder, HeadDatabase, LWC, Brewery, PhatLoots, CustomCommands, ChestShop

#### What is happening?

This message shows up in the console when the server is started.

27.12 12:23:40 [Server] Server thread/INFO Enabling ChestShop v3.11 (build 213)
27.12 12:23:40 [Server] Server thread/INFO Found locale en!
27.12 12:23:40 [Server] Server thread/WARN INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating table 'accounts'
27.12 12:23:40 [Server] Server thread/WARN INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating index 'accounts_uuid_idx' for table 'accounts
27.12 12:23:40 [Server] Server thread/WARN INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating index 'accounts_shortName_idx' for table 'accounts
27.12 12:23:40 [Server] Server thread/WARN INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating index 'accounts_name_idx' for table 'accounts
27.12 12:23:40 [Server] Server thread/WARN INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `accounts` (`name` VARCHAR NOT NULL , `shortName` VARCHAR NOT NULL , `uuid` VARCHAR NOT NULL , `lastSeen` BIGINT DEFAULT 0 NOT NULL , PRIMARY KEY (`shortName`) , UNIQUE (`name`,`uuid`) ) 
27.12 12:23:40 [Server] Server thread/WARN INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_uuid_idx` ON `accounts` ( `uuid` )
27.12 12:23:40 [Server] Server thread/WARN INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_shortName_idx` ON `accounts` ( `shortName` )
27.12 12:23:40 [Server] Server thread/WARN INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_name_idx` ON `accounts` ( `name` )
27.12 12:23:40 [Server] Server thread/WARN Server economy account setting '' doesn't seem to be the name of a known player! Please log in at least once in order for the server economy account to work.
27.12 12:23:40 [Server] Server thread/WARN INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating table 'items'
27.12 12:23:40 [Server] Server thread/WARN INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating index 'items_code_idx' for table 'items
27.12 12:23:40 [Server] Server thread/WARN INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `items` (`id` INTEGER PRIMARY KEY AUTOINCREMENT , `code` VARCHAR NOT NULL ) 
27.12 12:23:40 [Server] Server thread/WARN INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `items_code_idx` ON `items` ( `code` )

**Comment by Phoenix616** [comment] 2020-12-27 22:02
Not an issue and duplicate of #49. If you have information which is requested in that issue then please provide that there.

**Closed by Phoenix616** 2020-12-27 22:02 UTC
