### ISSUE TITLE
Economy username cannot be null

### ISSUE THREAD

**Issue by andrewkm** [ChestShop-authors/ChestShop-3#243] opened 2019-06-20 23:40 UTC
https://pastebin.com/raw/Tk2TtZnw
We have been getting this quite a bit lately.
We are using build 149.

Happens about 5-10 times a day on a very active chestshop based server.
So can consider is rare, none the less, it does happen continuously.

**Comment by Phoenix616** [comment] 2019-06-20 23:52
Duplicate of #204.

**Closed by Phoenix616** 2019-06-20 23:53 UTC
