### ISSUE TITLE
An idea

### ISSUE THREAD

**Issue by SurvivorTheReal** [ChestShop-authors/ChestShop-3#226] opened 2019-05-03 06:26 UTC
An idea, for those who open a shop together.
At the moment, there is no opportunity to give permission to a player to look into the chest what is a shop chest. So, what if there is a command which can give the permission to that player? The shopkeeper could give the permission to the chests one-by-one, or to all of the chests. This could make things easier. For example:the shopkeeper is not online, but one or more chest are empty. Then the other player, who also belongs to the shop can not even open the chest. However, if the shopkeeper can give permissions to players this won't happen.
I noticed one negative thing about this. With the permission, players can rob the shopkeeper if those players are not the trustful ones. But, is it possible to give permission only to put things into the chest? If yes, that would be great.
Thank you for reading this!
P.S: Sorry for not giving details about the server what I am playing on, but I don't have information about plugin versions, or anything other versions. Only the server version  what I know, it is 1.13.2 but in the close future there will be an 1.14.1 world running next to it. Furthermore, I can not speak english perfectly. So, if I have written something wrong.

**Comment by Phoenix616** [comment] 2019-05-03 10:44
Duplicate of #133.

The difficulty with this is that we would need to store per-shop information somewhere as the sign can't hold multiple names.

Theoretically it's already possible to do this by using LWC instead of the internal protection to protect shop chests.

**Closed by Phoenix616** 2019-05-03 10:45 UTC
