### ISSUE TITLE
Sign displays the translated name

### ISSUE THREAD

**Issue by nyancat-hu** [ChestShop-authors/ChestShop-3#580] opened 2024-01-01 09:43 UTC
### Is your feature request related to a problem? Please describe.

Is there any way to make the item name displayed in Sign become a translated name instead of English. I know it's possible to configure aliases for items, but imagine that I need to configure aliases for all items in Minecraft, which is equivalent to re localizing them. What a huge workload!

### Describe the solution you'd like

Let Sign automatically display the translated item name,just getI18NDisplayName

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I have checked that the latest build doesn't already implement the feature.

**Comment by Phoenix616** [comment] 2024-01-01 12:31
Duplicate of #398. See my comment there for why this isn't as easy as it might seem at first glance.

**Closed** 2024-01-01 12:32 UTC
Labels: enhancement
