### ISSUE TITLE
Problem with loggin in

### ISSUE THREAD

**Issue by Dasterman** [ChestShop-authors/ChestShop-3#163] opened 2018-08-31 14:00 UTC
Good day! Installed plugin for 1.13 version(now i have 1.13.1 server). After when i joined server, it gave me log below. Does it depend of nickname, as i could understand? Thanks for future reply^^.
P.S Server doesn't crash, plugin is been loaded correctly.

[16:38:53 WARN]: [ChestShop] Plugin ChestShop v3.9.3-SNAPSHOT (build 92) generated an exception while executing task 82
java.lang.StackOverflowError: null
    at org.sqlite.core.CoreStatement.<init>(CoreStatement.java:39) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
    at org.sqlite.jdbc3.JDBC3Statement.<init>(JDBC3Statement.java:21) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
    at org.sqlite.jdbc4.JDBC4Statement.<init>(JDBC4Statement.java:11) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
    at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:42) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
    at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
    at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
    at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
    at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:263) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
    at com.Acrobot.ChestShop.ORMlite.jdbc.JdbcDatabaseConnection.compileStatement(JdbcDatabaseConnection.java:147) ~[?:?]
    at com.Acrobot.ChestShop.ORMlite.stmt.mapped.MappedPreparedStmt.compile(MappedPreparedStmt.java:56) ~[?:?]
   at com.Acrobot.ChestShop.ORMlite.stmt.mapped.MappedPreparedStmt.compile(MappedPreparedStmt.java:45) ~[?:?]
   at com.Acrobot.ChestShop.ORMlite.stmt.StatementExecutor.queryForFirst(StatementExecutor.java:102) ~[?:?]
   at com.Acrobot.ChestShop.ORMlite.dao.BaseDaoImpl.queryForFirst(BaseDaoImpl.java:240) ~[?:?]
   at com.Acrobot.ChestShop.ORMlite.stmt.QueryBuilder.queryForFirst(QueryBuilder.java:380) ~[?:?]
   at com.Acrobot.ChestShop.ORMlite.stmt.Where.queryForFirst(Where.java:494) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.lambda$getAccountFromShortName$2(NameManager.java:115) ~[?:?]
   at com.Acrobot.Breeze.Collection.SimpleCache.get(SimpleCache.java:33) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getAccountFromShortName(NameManager.java:113) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getNewShortenedName(NameManager.java:280) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.storeUsername(NameManager.java:253) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getAccountFromShortName(NameManager.java:133) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getNewShortenedName(NameManager.java:280) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.storeUsername(NameManager.java:253) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getAccountFromShortName(NameManager.java:133) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getNewShortenedName(NameManager.java:280) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.storeUsername(NameManager.java:253) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getAccountFromShortName(NameManager.java:133) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getNewShortenedName(NameManager.java:280) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.storeUsername(NameManager.java:253) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getAccountFromShortName(NameManager.java:133) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getNewShortenedName(NameManager.java:280) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.storeUsername(NameManager.java:253) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getAccountFromShortName(NameManager.java:133) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getNewShortenedName(NameManager.java:280) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.storeUsername(NameManager.java:253) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getAccountFromShortName(NameManager.java:133) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getNewShortenedName(NameManager.java:280) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.storeUsername(NameManager.java:253) ~[?:?]
   at com.Acrobot.ChestShop.UUIDs.NameManager.getAccountFromShortName(NameManager.java:133) ~[?:?]

**Comment by Phoenix616** [comment] 2018-08-31 15:34
Duplicate of #162. Should already be fixed in build 93.

**Closed** 2018-08-31 15:35 UTC

**Comment by Dasterman** [comment] 2018-08-31 16:11
Great, thank you for reply, wait for new build^^
