### ISSUE TITLE
error

### ISSUE THREAD

**Issue by OneHitX** [ChestShop-authors/ChestShop-3#501] opened 2022-02-12 16:46 UTC
### What is happening?

[13:45:10 WARN]: [ChestShop] Plugin ChestShop v3.12.1-SNAPSHOT (build 343) generated an exception while executing task 33740
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:678) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
        at com.Acrobot.Breeze.Utils.QuantityUtil.parseQuantity(QuantityUtil.java:16) ~[ChestShop.jar:?]
        at com.Acrobot.ChestShop.Signs.ChestShopSign.getQuantity(ChestShopSign.java:256) ~[ChestShop.jar:?]
        at com.Acrobot.ChestShop.Signs.ChestShopSign.getQuantity(ChestShopSign.java:246) ~[ChestShop.jar:?]
        at com.Acrobot.ChestShop.Listeners.PostShopCreation.ShopCreationLogger.lambda$onShopCreation$0(ShopCreationLogger.java:24) ~[ChestShop.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1551]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.1.jar:git-Purpur-1551]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.1.jar:git-Purpur-1551]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### What did you expect to happen?

no error

### Plugin Version

ChestShop version 3.12.1-SNAPSHOT (build 343)

### Plugin Config

<details>
  <summary>Config</summary>

 ```yaml
 [Put the config here]
 ```

</details>

### Server Version

Current: git-Purpur-1551 (MC: 1.18.1)*

### Server Log

<details>
  <summary>Log</summary>

  ```
  [Your log here]
  ```

</details>

### What other plugins are you running?

ChestShop, Chunky, Citizens, ClearLag, CoreProtect, DeluxeMenus, Essentials, EssentialsSpawn, F3Name, FarmingUpgrade

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

**Comment by Phoenix616** [comment] 2022-02-12 18:00
Duplicate of #342

**Closed by Phoenix616** 2022-02-12 18:00 UTC
