### ISSUE TITLE
PlayerInteract and PacketPlayInBlockDig

### ISSUE THREAD

**Issue by Diinl** [ChestShop-authors/ChestShop-3#79] opened 2017-10-15 19:35 UTC
Spigot version: 1.12.2
Chestshop Version: 3.8.13-SNAPSHOT

Issue: Random server lockups, no tps drops :(. This may not or may be a chestshop problem but its the only thing I can think of currently.

Log file: https://pastebin.com/n1EDMmaG

**Comment by Phoenix616** [comment] 2017-10-25 13:46
Duplicate of #78

**Closed by Phoenix616** 2017-10-25 13:46 UTC
Labels: duplicate

**Comment by FrukTik** [comment] 2017-10-25 13:49
Why did you close my question without answering.
Can you fix this mistake? I crashed the server for 2 hours.

**Comment by Phoenix616** [comment] 2017-10-25 13:54
Your issue was a duplicate of another already opened issue. Please comment there if you have any further information to add and make sure to check yourself if there is a similar issue already opened in the future.
