### ISSUE TITLE
Client disconnects when buying from a playershop (JsonParseException)

### ISSUE THREAD

**Issue by unclesom** [ChestShop-authors/ChestShop-3#353] opened 2020-09-06 15:35 UTC
#### Plugin Version
3.11 (build 213)
 
 
#### Plugin Config
https://pastebin.pl/view/837a4ecb
 
#### Server Version
Paper 184 (1.16.2)
 

#### What other plugins are you running?
![image](https://user-images.githubusercontent.com/68922642/92329258-54ce6700-f034-11ea-91b9-bbe04a06d0fe.png)

#### What is happening?
When a player buys from a shop, the owner of the shop will be kicked from the server. This can be usually fixed with a server restart but usually reoccurs after the next restart. 

The message that the owner of the shop gets when kicked:
https://cdn.discordapp.com/attachments/735489735740358727/752182816556711996/unknown.png

**Comment by Phoenix616** [comment] 2020-09-06 15:51
Please test if this still happens on the latest development builds.

**Comment by unclesom** [comment] 2020-09-24 01:37
I tested the new development build and it seemed to work for a while until today when it started crashing again. Are there any chat plugins that would directly cause this crash?

**Comment by Phoenix616** [comment] 2020-09-24 11:48
It is highly unlikely that this error is caused by a plugin directly. It's either a Bug in the BungeeCord-Chat API, in Gson directly or maybe caused by a plugin not relocating Gson. For more information see SpigotMc/BungeeCord#2935 and the related [Spigot issue](https://hub.spigotmc.org/jira/browse/SPIGOT-6056).

**Comment by Phoenix616** [comment] 2020-11-20 15:46
As several people have asked how to remove the hover: The messages are using the [MineDown syntax](https://wiki.phoenix616.dev/library:minedown:syntax#events) to add the hover information so if you need to remove them due to this server issue then you can simply remove the `[text](hover)` to just say `text`.

E.g. the `SOMEBODY_BOUGHT_FROM_YOUR_SHOP` message would go from `[%buyer bought %item for %price.](&7In world: &f%world\n&7At position: &f%x/%y/%z)` to just `%buyer bought %item for %price.`. If course you could include the other information like the place in the message too.

I've also create a replacement [lang.en.yml file which does not use hover messages](https://gist.github.com/Phoenix616/6b85d36d98afbccf3ac5f9096bbbbaff) but includes some more information in the text directly instead of the hover if you just want to drop that in directly without defining your own syntax.

Hopefully I will be able to work around this issue by moving ChestShop to the kyori adventure text library soon once they fix some issues on the latest Java version. (Which would also allow for the plugin to run on pure CraftBukkit again)

**Comment by Phoenix616** [comment] 2020-12-01 18:50
Should be fixed with 51e9d5f267f03b36ceef75fac6945b98ad26562d now.

Please re-open the ticket if this issue still occurs with the builds including that commit.

**Closed by Phoenix616** 2020-12-01 18:50 UTC
Labels: server issue
