### ISSUE TITLE
Shop owners kicked by error when their shops are used

### ISSUE THREAD

**Issue by noodlelandmc** [ChestShop-authors/ChestShop-3#379] opened 2020-11-11 16:56 UTC
#### Plugin Version

 3.11.1-SNAPSHOT (build 240)
 
#### Plugin Config

<details>
  <summary>Config</summary>
  
 ```yaml

[config.txt](https://github.com/ChestShop-authors/ChestShop-3/files/5525507/config.txt)

 ```
 
 </details>
 
#### Server Version

 Paper version git-Paper-246 (MC 1.16.3)
 
#### Server Log

<details>
  <summary>Log</summary>

```
[Your log here]
[latest.log](https://github.com/ChestShop-authors/ChestShop-3/files/5525496/latest.log)

```

</details>

#### What is happening?

![image](https://user-images.githubusercontent.com/72227742/98839731-e7fc9200-2413-11eb-9a90-ece7202816a1.png)

#### What did you expect to happen?

I expected to not be kicked from the server after someone used my shop.

#### Additional context

This has been an ongoing problem for months now and requires a server restart to temporarily fix it until the issue starts popping up again seemingly randomly.

**Comment by Phoenix616** [comment] 2020-11-11 17:56
This is an issue with your server software not handling chat hover events correctly, not with the plugin. (Duplicate of #353)

**Closed by Phoenix616** 2020-11-11 17:56 UTC
