### ISSUE TITLE
Hi! I haven't studied the plugin very well, but I'm not sure if this feature is there. Is it possible to make it so that when a store is created using a sign, I would have the opportunity to change the letter " B "to" &1Buy " in blue, I would also like the word buy or sell to be at the top before the player's nickname. I would also like to know if it is possible to write the id of the subject, and not its name?

### ISSUE THREAD

**Issue by Pikachu2p** [ChestShop-authors/ChestShop-3#477] opened 2021-09-27 14:56 UTC
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

Hi! I haven't studied the plugin very well, but I'm not sure if this feature is there. Is it possible to make it so that when a store is created using a sign, I would have the opportunity to change the letter " B "to" &1Buy " in blue, I would also like the word buy or sell to be at the top before the player's nickname. I would also like to know if it is possible to write the id of the subject, and not its name?

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I have checked that the latest build doesn't already implement the feature.

**Comment by Phoenix616** [comment] 2021-09-28 13:01
Duplicate of #237

**Closed by Phoenix616** 2021-09-28 13:01 UTC
Labels: enhancement
