### ISSUE TITLE
Could not pass event AccountCheckEvent to ChestShop

### ISSUE THREAD

**Issue by andris155** [ChestShop-authors/ChestShop-3#205] opened 2019-02-18 14:15 UTC
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version
[The full plugin version that you are running from /version ChestShop]
ChestShop version 3.9.3-SNAPSHOT (build 113)

#### Plugin Config
[The full config.yml file of ChestShop]
https://pastebin.com/sRitM2zh
 
#### Server Version
[The full server version that you are running from /version]
```
18.02 15:13:37 [Server] INFO This server is running Paper version git-Paper-524 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
18.02 15:13:37 [Server] INFO Previous version: git-Paper-521 (MC: 1.13.2)
18.02 15:13:37 [Server] INFO Checking version, please wait...
18.02 15:13:38 [Server] INFO You are 1 version(s) behind
```
 
#### Server Log
[The full latest.log file]
I send if need this.

#### What other plugins are you running?
[List of your plugins, ideally with the version] 
`18.02 15:14:07 [Server] INFO Plugins (97): AdditionsAPI, AdminVedelem, antiRedstoneClock, AnvilRestrict, AreaShop, AsyncWorldEdit, BestViewDistance, BuntetesLogolo, ChangeSkin, ChatControl, ChestCommands, ChestShop, Citizens, CitizensCMD, CombatLogX, CommandHook, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CrateReloaded, CrazyAuctions, CreativeNbtControl, Duels, EnderContainers, EntityDetection*, EpicHeads, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, GriefPrevention, GriefPreventionFlags, HideAndSeek, HonapStaffja, iDisguise, JukeBox, Kezdes, LockettePro, Lottery, LuckPerms*, mcMMO, MineMarket-Universal, MobArena, MobFarmManager, MobHeads, Multiverse-Core, Multiverse-NetherPortals, MyCommand*, MyPet, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, Paintball, PickupSpawners, PlaceholderAPI, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan*, PocketGames, PomaAdditions, ProtocolLib*, RandomTeleport, RedstoneClockDetector*, RestrictedCreative, Ridables, Shopkeepers, SignEdit*, StackMob, Stats, SuperLuckyBlock-Pro, SzulinapiTuzijatek, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, ViaBackwards*, ViaVersion*, Votifier, VotingPlugin, VoxelSniper*, WDLCompanion*, WDLCompanionGriefPreventionSupport*, WorldBorderPearlBlock*, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge`

#### What is happening?
[Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures and the full error log!] 
```
[20:16:47] [Server thread/ERROR]: Could not pass event AccountCheckEvent to ChestShop v3.9.3-SNAPSHOT (build 113)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-524]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-524]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-524]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-524]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.preparePreTransactionEvent(PlayerInteract.java:158) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:129) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[patched_1.13.2.jar:git-Paper-524]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-524]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-524]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-524]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320) ~[patched_1.13.2.jar:git-Paper-524]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:466) ~[patched_1.13.2.jar:git-Paper-524]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1362) ~[patched_1.13.2.jar:git-Paper-524]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-524]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-524]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-524]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-524]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-524]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-524]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-524]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-524]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: Economy username cannot be null
	at com.earth2me.essentials.api.Economy.getUserByName(Economy.java:65) ~[?:?]
	at com.earth2me.essentials.api.Economy.playerExists(Economy.java:359) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.hasAccount(Economy_Essentials.java:281) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.hasAccount(Economy_Essentials.java:291) ~[?:?]
	at net.milkbowl.vault.economy.AbstractEconomy.hasAccount(AbstractEconomy.java:15) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Economy.Plugins.VaultListener.onAccountCheck(VaultListener.java:125) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor727.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-524]
	... 23 more
```

**Comment by Phoenix616** [comment] 2019-02-18 15:56
Potential duplicate of #197, the root of the issue here is that Vault is trying to use the null username of an OfflinePlayer (which is the case when the player is unknown/never joined before) instead of using the UUID.

The actual shop sign that is causing this issue would be helpful in determining if it really is the same issue though.

**Closed** 2019-09-29 10:58 UTC
Labels: plugin issue
