### ISSUE TITLE
Warnings in console on every startup of server

### ISSUE THREAD

**Issue by IITFA** [ChestShop-authors/ChestShop-3#216] opened 2019-04-10 11:52 UTC
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version
[The full plugin version that you are running from /version ChestShop]
 ChestShop version 3.9.2 (build 86)
#### Plugin Config
[The full config.yml file of ChestShop]
 https://hastebin.com/oleyukatuc.makefile
#### Server Version
[The full server version that you are running from /version]
 CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
#### Server Log
[The full latest.log file]
https://hastebin.com/redizecaje.sql
#### What other plugins are you running?
[List of your plugins, ideally with the version] 
too many
#### What is happening?
[Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures and the full error log!] 
Chest Shops seems to work, but the above warnings show up on every server restart
#### What did you expect to happen?
[Explain what you expected to happen after performing the previously described steps]
no warnings or errors
Please provide any additional info below
[And delete the lines in square brackets]

**Comment by Phoenix616** [comment] 2019-04-10 12:45
Duplicate of #49. These aren't warnings but info messages as indicated by the "INFO" in the actual message body, they just get logged as warnings by Bukkit's logger for some reason. Not sure exactly why ORMLite is sending these messages in some cases and not others (I never got them when testing) so there isn't really an in-plugin solution for it.

However ORMLite seems to be using LocalLog so you should be able to use the `com.j256.ormlite.logger.level` system property to set the log level to "WARN" to only log warning messages. (by adding `-Dcom.j256.ormlite.logger.level=WARN` to your server start arguments) but again: I never got these messages in the first place so I can't really test this approach.

You might also want to update to the latest [1.12 builds](https://ci.minebench.de/job/ChestShop-3-1.12/).

**Closed by Phoenix616** 2019-04-10 12:45 UTC
