### ISSUE TITLE
Huge error when /ChestShop:ItemInfo on Brewery Drink

### ISSUE THREAD

**Issue by strahil211** [ChestShop-authors/ChestShop-3#456] opened 2021-06-16 14:17 UTC
#### Plugin Version
3.12 (build 307)
 
 
#### Plugin Config
Default 

 
#### Server Version
Airplane version git-Airplane-"4144b28" (MC: 1.16.5)
 
 
#### Server Log

<details>
  <summary>Log</summary>

```
[[13:58:04] [Server thread/INFO]: RCCrafters issued server command: /chestshop:iteminfo
[13:58:04] [Server thread/ERROR]: Could not pass event ItemInfoEvent to ChestShop v3.12 (build 307)
java.lang.StackOverflowError: null
	at java.lang.String.indexOf(String.java:1621) ~[?:?]
	at java.lang.String.indexOf(String.java:1578) ~[?:?]
	at com.Acrobot.ChestShop.Libs.Kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.determineFormatType(LegacyComponentSerializerImpl.java:131) ~[?:?]
	at com.Acrobot.ChestShop.Libs.Kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.decodeTextFormat(LegacyComponentSerializerImpl.java:153) ~[?:?]
	at com.Acrobot.ChestShop.Libs.Kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:223) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:207) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:255) ~[?:?]
	at com.Acrobot.ChestShop.Libs.MineDown.Replacer.replaceIn(Replacer.java:187) ~[?:?]]
```

</details>

#### What other plugins are you running?
AntiXrayHeuristics, AutomatedCrafting, BetterTeams, BettingGames, BottledExp, Brewery, ChestShop, Chunky, ChunkyBorder, CMI, CMIEInjector*, CMILib, CrazyAuctions, CryptoMarket, CustomWings, DualWield*, Elevator, GCoreLegacy, GSit, HeadDatabase, ImageMaps, InventorySaver, Jobs, LuckPerms, MarriageMaster, mcMMO, Minepacks, MiniBoardGames, MobFarmManager, Pl3xMap, ProtocolLib, SpecializedCrates, Spleef*, Stocks*, SurvivalInvisiframes, TempFly, TogglePVP, TradeMe, TryMe, Vault, ViaVersion, Vulcan, WorldEdit, WorldGuard, WorldGuardExtraFlags

#### What is happening?
Brewery adds Alcohol to the game, when holding a brew and doing /ChestShop:ItemInfo it throws a near endless error (I only posted 5% of it because its all the same after a few lines)
This error did not happen on previous ChestShop version!
It still displays the iteminfo in chat, the only problem is the huge console spam.

#### What did you expect to happen?
No console error

**Comment by Phoenix616** [comment] 2021-06-16 14:20
Can you please provide the NBT data of one such item for me to test it with?

**Comment by Phoenix616** [comment] 2021-06-16 14:22
Also it's a duplicate issue, so ideally provide the NBT data there.

Duplicate of #454

**Closed by Phoenix616** 2021-06-16 14:22 UTC
