### ISSUE TITLE
SQL Driver Error

### ISSUE THREAD

**Issue by ApertureDevelopment** [ChestShop-authors/ChestShop-3#149] opened 2018-08-04 20:11 UTC
#### Plugin Version
3.9.0 ( build \#52 )
 
#### Server Version
git-Spigot-642f6d2-57ab4cf ( MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT )
 
#### Server Log
```
[Server thread] ERROR com.Acrobot.ChestShop.ORMlite.db.SqliteDatabaseType - WARNING: you seem to not be using the Xerial SQLite driver.  See ORMLite docs on SQLite: http://ormlite.com/docs/sqlite
[22:01:58 WARN]: [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating table 'items'
[22:01:58 WARN]: [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `items` (`id` INTEGER PRIMARY KEY AUTOINCREMENT , `code` VARCHAR NOT NULL ,  UNIQUE (`code`)) 
[22:01:58 WARN]: [Server thread] ERROR com.Acrobot.ChestShop.ORMlite.db.SqliteDatabaseType - WARNING: you seem to not be using the Xerial SQLite driver.  See ORMLite docs on SQLite: http://ormlite.com/docs/sqlite
[22:01:58 WARN]: [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating table 'accounts'
[22:01:58 WARN]: [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating index 'accounts_uuid_idx' for table 'accounts
[22:01:58 WARN]: [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating index 'accounts_shortName_idx' for table 'accounts
[22:01:58 WARN]: [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating index 'accounts_name_idx' for table 'accounts
[22:01:59 WARN]: [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `accounts` (`name` VARCHAR NOT NULL , `shortName` VARCHAR NOT NULL , `uuid` VARCHAR NOT NULL , `lastSeen` BIGINT DEFAULT 0 NOT NULL , PRIMARY KEY (`shortName`) , UNIQUE (`name`,`uuid`) ) 
[22:01:59 WARN]: [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_uuid_idx` ON `accounts` ( `uuid` )
[22:02:00 WARN]: [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_shortName_idx` ON `accounts` ( `shortName` )
[22:02:00 WARN]: [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_name_idx` ON `accounts` ( `name` )
```

#### What is happening?
This error and warning happens on every start

#### What did you expect to happen?
That this doesnt show up.

Please provide any additional info below

This is not related to the issue https://dev.bukkit.org/projects/chestshop/issues/1073 or https://github.com/ChestShop-authors/ChestShop-3/issues/49
Because the fix stated there ( deleting and letting the server re-create the db files ) didnt work

**Comment by Phoenix616** [comment] 2018-08-05 17:29
It IS a duplicate of these issues, they are also just warnings/info messages, not actual errors as stated in the message.

**Closed** 2018-08-05 17:29 UTC
Labels: duplicate

**Comment by ApertureDevelopment** [comment] 2018-08-05 17:40
And "ERROR" is just imagined or what?

**Comment by Phoenix616** [comment] 2018-08-12 20:46
It clearly says "WARNING", no idea why ORMlite doesn't use the correct log level, you would have to report it to them directly.

It would also be extremely helpful if you could provide some additional information about your system and the conditions when this message occurs as I personally have never been able to reproduce it on any of my test systems.
