### ISSUE TITLE
Could not pass event CurrencyAddEvent to ChestShop

### ISSUE THREAD

**Issue by imDaniX** [ChestShop-authors/ChestShop-3#209] opened 2019-03-16 18:15 UTC
#### Plugin Version
3.9.3-SNAPSHOT (build 115)

#### Plugin Config
default

#### Server Version
git-Paper-566 (MC: 1.13.2)

#### Server Log
Don't think that full log is needed.
https://hastebin.com/feqoduyeki.sql

#### What other plugins are you running?
AdvancedPortals, Arconix*, AuthMe, ChangeSkin, Chatty*, ChestShop, ClearLag*, CoreProtect, EssentialsX, EssentialsXGeoIP, EssentialsXSpawn, F3Name, FastAsyncWorldEdit*, HolographicDisplays, Jobs, LuckPerms, Magic, Marriage*, Multiverse-Core*, PlaceholderAPI, ProtocolLib*, ProtocolSupport, ProtocolSupportStuff, RFChairs, SafeTrade, ServerListPlus*, TitleManager*, UltimateTimber, Vault*(1.7.1-b91), WorldBorder*, WorldEdit, WorldGuard

#### What is happening?
When player have enough money to buy something - nothing happens but error.

**Comment by Phoenix616** [comment] 2019-03-16 18:19
Potential duplicate of #194, the root of the issue here is that Vault is trying to use the null username of an OfflinePlayer (which is the case when the player is unknown/never joined before) instead of using the UUID.

The actual shop sign that is causing this issue would be helpful in determining if it really is the same issue though.

**Closed** 2019-03-17 15:48 UTC
