### ISSUE TITLE
chestshop.admin permissions prevents buying from shop.

### ISSUE THREAD

**Issue by andrewkm** [ChestShop-authors/ChestShop-3#182] opened 2018-11-17 18:51 UTC
Use spigot 1.13.2
Latest Chestshop 1.13.2 from jenkins.

With chestshop.admin permission, buying is impossible.
The chest simply opens up.
Config is as such: https://pastebin.com/raw/e9G6xDDL

Changing:
`ALLOW_SIGN_CHEST_OPEN: true`
To:
`ALLOW_SIGN_CHEST_OPEN: false`

Prevents the chest from opening up when right clicking however now right clicking gives off the LWC notice and still doesn't proceed with the buy.
Example: https://i.imgur.com/WKAEEQS.png

Left click for selling as well doesn't work.

Only solution is to disable chestshop.admin.
Please help.

**Comment by Phoenix616** [comment] 2018-11-17 19:12
Duplicate of #179

**Closed by Phoenix616** 2018-11-17 19:12 UTC
Labels: duplicate

**Comment by andrewkm** [comment] 2018-11-19 17:55
@Phoenix616 this is not a duplicate to be honest, the other report is based on OPs.
We do not use OPs as it is the worst practice when running a server.

We strictly control our permissions ourselves.

I consider this report to be most accurate out of the three.
