### ISSUE TITLE
Geyser compatibility (if possible).

### ISSUE THREAD

**Issue by Vehzx** [ChestShop-authors/ChestShop-3#464] opened 2021-07-08 01:29 UTC
Hi, I use geyser to support bedrock crossplay.

I run a towny server that's economy based using ChestShop, but i'm running into an issue where the bedrock players can't any chestshops because bedrock players using Geyser have a . at the start of their name.

For example: .Vehzx

So when trying to sell something, the plugin doesn't recognise the username and doesn't allow them to sell / buy etc.

This means they have no way of gaining money in-game.

If there is any chance of this being supported, I would greatly appreciate it, thanks.

Link to Geyser (if you have never heard of it): https://geysermc.org

**Comment by Phoenix616** [comment] 2021-07-08 09:04
Duplicate of #383

**Closed** 2021-07-08 09:04 UTC
Labels: enhancement
