### ISSUE TITLE
How to setup Xerial SQLite Driver?

### ISSUE THREAD

**Issue by TheDGOfficial** [ChestShop-authors/ChestShop-3#84] opened 2017-11-19 21:59 UTC
I see this erros on log:
`[00:52:04] [Server thread/ERROR]: WARNING: you seem to not be using the Xerial SQLite driver.  See ORMLite docs on SQLite: http://ormlite.com/docs/sqlite
`

How to setup Xerial SQLite Driver?

**Comment by Phoenix616** [comment] 2017-11-19 22:11
Duplicate of #49

**Closed by Phoenix616** 2017-11-19 22:11 UTC
