### ISSUE TITLE
Set pricelimits

### ISSUE THREAD

**Issue by felipeleite5w** [ChestShop-authors/ChestShop-3#286] opened 2019-12-23 14:01 UTC
Hi, I wanna set pricelimits for some items

I did with an item and it worked however i dont know how to do with multiple items...

Could anyone help me?
The IDS are 4404 , 4403 , 4402 , 4401
Chestshop version 3.7.6

In this file you can configure maximum and minimum prices for items (when creating a shop).
max:
buy_price:
itemID: 4403
'4403': 2
sell_price:
'4403': 2
min:
buy_price:
'4403': 1
sell_price:
'4403': 1

I know its a weird price, dont ask me why .-.

https://gist.github.com/felipeleite5w/73e7592f0d358a8ae655388bea846541

**Comment by Phoenix616** [comment] 2019-12-23 14:31
Duplicate of #279

**Closed by Phoenix616** 2019-12-23 14:31 UTC
