### ISSUE TITLE
Ignore NBT label of the item

### ISSUE THREAD

**Issue by GiantTeddy** [ChestShop-authors/ChestShop-3#513] opened 2022-04-16 22:11 UTC
### Is your feature request related to a problem? Please describe.

The sign provide the nbt to distinguish enchantbooks, they are useful. But something like beehives also contain NBT labels in it, and they are not really matter. 

Can we create a shop which ignores NBT label.

### Describe the solution you'd like

something like Beehive#? to indicate NBT label is ignored.

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I have checked that the latest build doesn't already implement the feature.

**Comment by Phoenix616** [comment] 2022-04-17 15:38
Duplicate of #471

**Closed by Phoenix616** 2022-04-17 15:38 UTC
Labels: enhancement
