### ISSUE TITLE
Possibility for a player to give access to his shop to someone else

### ISSUE THREAD

**Issue by Over2Craft-mc** [ChestShop-authors/ChestShop-3#450] opened 2021-05-29 08:27 UTC
As a player, I would like my friend to be able to refill the stock of my shop
I would need something that allow me to specify that my friend have access to this a specific Shop

An easy way would be to use an other sign which would be sticked to another face of the chest with the name of the player we would like to give access to

![image](https://user-images.githubusercontent.com/74878280/120063634-7959eb80-c068-11eb-9469-368905a755a9.png)

**Comment by Phoenix616** [comment] 2021-05-29 12:31
Duplicate of #404.

**Closed by Phoenix616** 2021-05-29 12:31 UTC
Labels: enhancement
