### ISSUE TITLE
Add possibility to write on line 2 "Amount:" (and add alias to translate in other languages) and on line 3 add alias for "B" and "V" 

### ISSUE THREAD

**Issue by Deernose** [ChestShop-authors/ChestShop-3#505] opened 2022-02-24 05:20 UTC
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/32472199/155462763-912b78ab-a395-4fa2-ad34-4eb1199f055d.png)

Can you make this works? and also if its possible add alias to custumize in config file "Sell"  "Buy" and "Amount" as a translation proposal 

### Describe the solution you'd like

In the forums here in Brazil I saw many customized chestshops that instead of using B 1:1 S to buy and sell, they used C 1:1 V of "comprar" and "vender"(the translation in portuguese), if it were possible to create alternatives that would be amazing 

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I have checked that the latest build doesn't already implement the feature.

**Comment by Deernose** [comment] 2022-02-24 05:26
also i used essentials to change the lines with "/sign" command and works very well, this is a very useful feature for moderators that can be implemented
![image](https://user-images.githubusercontent.com/32472199/155463396-5e605470-f8df-4b0a-a3f5-ab27dfe93d7a.png)

**Comment by Phoenix616** [comment] 2022-02-24 10:15
Duplicate of #237

**Closed** 2022-02-24 10:16 UTC
Labels: duplicate, enhancement
