### ISSUE TITLE
Extreme Amounts of tps lag caused by ChestShop PacketPlayInBlockDig PlayerInteract

### ISSUE THREAD

**Issue by LogGits** [ChestShop-authors/ChestShop-3#76] opened 2017-09-24 06:09 UTC
Version: 3.8.13-SNAPSHOT (build 31)

I have noticed my tps drop down to 8 on my dedicated server. I looked into it and found that PacketPlayInBlockDig PlayerInteractEvent was using upwards of 800% of the tick https://gyazo.com/039f9f68e239e48ec440ddb75ae70a69. No errors were present in console and i don't know what is causing this (I don't know how to reproduce). But it keeps happening.

**Comment by Phoenix616** [comment] 2017-09-24 11:38
Please provide the full timings as well as information about how your server is setup, especially your economy plugin.

Issues like this can often be caused by slow economy transactions. E.g. if you have a slow connection to a database on another machine or use file based economies with slow file write and read speeds on an hd and not an ssd.

An alternative to improving the economy setup would be to set the SHOP_INTERACTION_INTERVAL higher in the config to stop players from spamming shops.

**Comment by LogGits** [comment] 2017-09-25 13:59
> especially your economy plugin.
rrrrr
We are using essentials and vault for our economy.

> Issues like this can often be caused by slow economy transactions.

Oh that is interesting to know.

> An alternative to improving the economy setup would be to set the SHOP_INTERACTION_INTERVAL higher in the config to stop players from spamming shops.

thanks for the suggestion i will try this :)


> Please provide the full timings as well as information about how your server is setup, especially your economy plugin.

I will send you this information on bukkit :)

**Comment by LogGits** [comment] 2017-09-26 02:33
https://gyazo.com/844fba58e01f9a075ea9d11b13277171

**Comment by Phoenix616** [comment] 2017-09-26 12:59
You seem to be running in offline mode without forwarding IP addresses or online UUIDs from a bungee, is that correct?

**Comment by LogGits** [comment] 2017-09-27 00:41
no Its online mode

**Comment by Phoenix616** [comment] 2017-09-27 19:08
Your timings clearly state that your server has online mode disabled and bungeecord set to false in the spigot.yml. I have to assume that you are also having offline mode player UUIDs because of that (this is important for the error). Please check that. (and if you are indeed using offline mode player UUIDs check if the same happens with online mode ones)

**Comment by LogGits** [comment] 2017-09-29 08:50
I know it says that but this is in my server.properties: https://gyazo.com/3fbfed947f10252a60945c18678837c8
and yes bungeecord is false in the spigot.yml.
How do I check if offlinemode player UUIDs are being used?

**Comment by Phoenix616** [comment] 2017-09-29 17:08
Offline UUIDs are version 3 ones where online UUIDs are version 4. So just look if the first number in the third group of your UUID is a 3 or a 4 when you log in.

**Comment by LogGits** [comment] 2017-10-01 02:11
The only one with a 3 in that group is the name of the shop. The rest of them have 4.

**Comment by LogGits** [comment] 2017-10-04 00:31
oh god it went to 2000+:
https://gyazo.com/3abb616881641101adf2f83f9a342432
Players keep getting timed out.

**Comment by Phoenix616** [comment] 2017-10-04 11:31
Please provide your server log from when this happens. Also please provide the log from when your server starts up.

**Comment by LogGits** [comment] 2017-10-04 13:09
Nothing appears in console when the lag occurs.
However during startup i get a xerial driver thing. I found out the 1 player leftclicking the sign can cause all players on the server to time out. I changed interaction interval to 600 il see if that helps.

**Comment by Phoenix616** [comment] 2017-10-04 17:56
As I said, please provide your logs and let me decide whether or not there is something in there that could help us track down that issue.

**Comment by Phoenix616** [comment] 2017-10-29 23:04
Commit 2d45dcd on the no-offline-player branch might fix this issue. (The corresponding build number is [36](https://ci.minebench.de/job/ChestShop-3/36/))

**Comment by LogGits** [comment] 2017-11-04 08:35
@Phoenix616 This build has seemed to resolve the issue. Thank you so much!

**Comment by Phoenix616** [comment] 2017-11-04 14:25
Ok, closing this issue then. If you notice any bugs with the changed version please open a new one.

**Closed by Phoenix616** 2017-11-04 14:25 UTC
